services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    environment:
      - DD_API_KEY=6f50bda0988e7bf1517fb53547dec44b
      - DD_SITE=us3.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    ports:
      - "8126:8126"  # Expose port 8126 for APM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - datadog-net

  python-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-api
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=python-api
      - DD_ENV=apm-test
      - DD_VERSION=1.0
      - DD_TRACE_AGENT_PORT=8126  # Explicitly set the trace agent port
    ports:
      - "5000:5000"
    depends_on:
      - datadog-agent
    networks:
      - datadog-net

networks:
  datadog-net:
    driver: bridge
